version: '3'
services:
    lanefollow:
        image: duckietown/dt-notebook:daffy
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /duckietown
        networks:
        - duckietown-docker-net
        volumes:
        - ./catkin_ws:/duckietown/catkin_ws
        - ./utils:/duckietown/utils
        - ./custom:/duckietown/custom
        - ./sim_ws:/duckietown/sim_ws
        - ./simulation:/duckietown/simulation
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ./.fifos:/fifos
        environment:
          #- "ROS_MASTER_URI=http://sim:11311"
        - "HOSTNAME=default"
        - "VEHICLE_NAME=default"
        - "DISPLAY=:99"
        expose:
        - "8888"
        ports:
        - "8888:8888"
networks:
    duckietown-docker-net:
